package com.valentinerutto.divinedatagpt.data.models

/**
 * A single Bible verse, always loaded from the local Room/FTS4 table.
 *
 * This is never generated by the model — it's read straight from the
 * on-device verse database and passed to Gemma as grounding context.
 * The UI renders this class directly, so a citation shown to the user
 * can never be a hallucinated or garbled quote.
 */
data class VerseCitation(
    val id: Int,          // e.g. "PHP.4.6"
    val book: Int,
    val chapter: Int,
    val verse: Int,
    val text: String,
    val translation: String
) {
    val reference: String get() = "$book $chapter:$verse"
}

enum class MessageRole { USER, ASSISTANT }

data class ChatMessage(
    val id: String,
    val role: MessageRole,
    val content: String,
    val citedVerse: VerseCitation? = null,
    val isStreaming: Boolean = false,
    val timestamp: Long = System.currentTimeMillis()
)

/** A tappable starter prompt shown in the empty state. */
data class PromptSuggestion(val id: String, val label: String, val fullPrompt: String)

/**
 * Token budget state, surfaced as a small usage indicator in the top bar.
 * Ticks down as the user sends messages; resets daily; a premium
 * entitlement can raise dailyBudget or set it to null for unlimited.
 */
data class TokenBudgetState(
    val tokensUsedToday: Int,
    val dailyBudget: Int?,     // null = unlimited (premium)
    val isPremium: Boolean
) {
    val isExhausted: Boolean get() = dailyBudget != null && tokensUsedToday >= dailyBudget
}

data class ReflectionUiState(
    val sessionTitle: String = "Reflect",
    val messages: List<ChatMessage> = emptyList(),
    val dailyVerse: VerseCitation? = null,
    val promptSuggestions: List<PromptSuggestion> = emptyList(),
    val inputText: String = "",
    val isGenerating: Boolean = false,
    val crisisTriggered: Boolean = false,
    val tokenBudget: TokenBudgetState = TokenBudgetState(0, 8000, isPremium = false),
    val showPaywall: Boolean = false
) {
    val isEmptyState: Boolean get() = messages.isEmpty() && !crisisTriggered
}